django-code/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import CustomLoginView, CustomPwdChangeView, register

app_name = 'accounts'

urlpatterns = [
    path('login', CustomLoginView.as_view(),name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('register', register, name='register'),
    path('pwd_change', CustomPwdChangeView.as_view(),name='pwd_change'),
]

django-code/carts/urls.py
from django.urls import path

from carts.views import cart_detail, cart_add, cart_remove

app_name = 'carts'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove')
]

django-code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('health', include('health_check.urls')),
]

django-code/orders/urls.py
from django.urls import path

from orders.views import checkout, order_complete, order_history

app_name = 'orders'

urlpatterns = [
    path('checkout', checkout, name='checkout'),
    path('order-complete/<int:order_id>', order_complete, name='order_complete'),
    path('order-history', order_history, name='order_history')
]

django-code/products/urls.py
from django.urls import path

from products.views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('category/<slug:category_slug>/<int:category_id>', product_list, name='category_product_list'),
    path('detail/<int:id>', product_detail, name='product_detail'),
]

django-code/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" nonce="{{ CSP_NONCE }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" nonce="{{ CSP_NONCE }}">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'products/css/listing.css' %}" rel="stylesheet">
    <link href="{% static 'products/css/category.css' %}" rel="stylesheet">
    <link href="{% static 'products/css/price_filter.css' %}" rel="stylesheet">
    <link href="{% static 'products/css/detail.css' %}" rel="stylesheet">
    <link href="{% static 'orders/css/order_history.css' %}" rel="stylesheet">
    
    <link rel="icon" href="{% static 'image/favicon.png' %}" type="image/png">
</head>
<body>
    
    <header>
        {% include "header.html" %}
    </header>
    <main>
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </main>
    <footer class="py-3 my-4"> 
        {% include "footer.html" %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" nonce="{{ CSP_NONCE }}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'products/js/input_filter.js' %}"></script>

</body>
</html>

django-code/templates/footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3"> 
    <li class="nav-item">
        <a href="#" class="nav-link px-2 text-body-secondary">
        Home
        </a>
    </li> 
    <li class="nav-item">
        <a href="#" class="nav-link px-2 text-body-secondary">Features</a>
    </li> 
    <li class="nav-item">
        <a href="#" class="nav-link px-2 text-body-secondary">Pricing</a>
    </li> 
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a>
    </li> 
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">
        About</a>
    </li> 
</ul> 
<p class="text-center text-body-secondary">
    © 2025 Company, Inc
</p> 

django-code/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light mb-4">
    <div class="container">
        <a class="navbar-brand fw-bold" href="{% url 'products:product_list' %}">E-commerce Store</a>
        <div class="collapse navbar-collapse">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'carts:cart_detail' %}">
                            <div class="cart-icon-container">
                                <img 
                                src="{% static 'image/cart-nav.svg' %}" 
                                alt="cart-nav-icon" 
                                class="cart-nav-icon"
                                >
                                {% if cart|length > 0 %}
                                    <span class="badge bg-primary rounded-pill">{{ cart|length }}</span>
                                {% endif %}
                            </div>
                            
                        </a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown">
                            <button 
                                class="btn btn-light dropdown-toggle" 
                                type="button" 
                                id="dropdownMenuButton" 
                                data-bs-toggle="dropdown" 
                                aria-expanded="false"
                                >
                                <div class="user-avatar">
                                    {% if user.avatar %}
                                        <img src="{{ user.avatar }}" alt="{{ user.get_initial }}" class="avatar-img">
                                    {% else %}
                                        <span 
                                            class="avatar-initials"
                                            id="avatar-initials-main"
                                            >
                                            {{ user.get_initial }}
                                        </span>
                                    {% endif %}
                                </div>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <li>
                                    <a class="dropdown-item" href="{% url 'orders:order_history' %}">
                                        Lịch sử đơn hàng
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'accounts:pwd_change' %}">
                                        Đổi mật khẩu
                                    </a>
                                </li>
                                <li>
                                    <form method="post" action="{% url 'accounts:logout' %}" class="logout-form">
                                        {% csrf_token %}
                                        <button type="submit" class="dropdown-item">Đăng xuất</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                        
                        
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.path }}">
                            Đăng nhập
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                            Đăng ký
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% comment %} get random color of the user and assign into `user-avatar-color` variable {% endcomment %}
<style nonce="{{ CSP_NONCE }}"> 
    :root { 
        --user-avatar-color: {{ user.get_avatar_color }};
    }
</style>