django-code/carts/urls.py
from django.urls import path

from carts.views import cart_detail, cart_add, cart_remove

app_name = 'carts'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove')
]

django-code/e_commerce_old/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from e_commerce.views import product, user, cart, review, order

app_name = 'e_commerce'

urlpatterns = [
    path('', product.product_list, name='product_list'),
    path('category/<slug:category_slug>/<int:category_id>', product.product_list, name='category_product_list'),
    path('health', include('health_check.urls')),
    path('product/<int:id>', product.product_detail, name='product_detail'),
    path('login', user.CustomLoginView.as_view(),name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('register', user.register, name='register'),
    path('pwd_change', user.CustomPwdChangeView.as_view(),name='pwd_change'),
    path('cart/', cart.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>', cart.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>', cart.cart_remove, name='cart_remove'),
    path('checkout', order.checkout, name='checkout'),
    path('order-complete/<int:order_id>', order.order_complete, name='order_complete'),
    path('submit_review/<int:product_id>', review.submit_review, name='submit_review'),
]

django-code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('health', include('health_check.urls')),
]

django-code/products/urls.py
from django.urls import path

from products.views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('category/<slug:category_slug>/<int:category_id>', product_list, name='category_product_list'),
    path('detail/<int:id>', product_detail, name='product_detail'),
]

django-code/e_commerce_old/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import AppUser, Order, Review

class AppUserCreationForm(UserCreationForm):

    avatar = forms.URLField(
        required=False, 
        help_text='Optional: Link to your profile picture.',
        label="Ảnh đại diện",
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    email = forms.EmailField(
        required=True,
                widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta(UserCreationForm.Meta):
        model = AppUser
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'username','email')

        labels = {
            'first_name': 'Tên',
            'last_name': 'Họ',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if 'password1' in self.fields:
            self.fields['password1'].label = 'Mật khẩu'
            
        if 'password2' in self.fields:
            self.fields['password2'].label = 'Xác nhận mật khẩu'

class AppUserChangeForm(UserChangeForm):
    avatar = forms.URLField(
        required=False, 
        help_text='Optional: Link to your profile picture.',
        label="Ảnh đại diện",
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = AppUser
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class OrderForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=150, 
        label= "Tên",
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    last_name = forms.CharField(
        max_length=150, 
        label= "Họ",
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    email = forms.EmailField(
        max_length=254, 
        label= "Email",
        help_text= "Email đã đăng ký",
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Order
        fields = ['phone_number', 'address']
        
        widgets = {
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'phone_number': 'Số  điện thoại',
            'address': 'Địa chỉ'
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content']

        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'content': 'Nội dung'
        }

django-code/e_commerce_old/views/cart.py
from django.http import HttpRequest
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.views.decorators.cache import cache_control

TEMPLATE_FOLDER_NAME = 'e_commerce'

from e_commerce.forms import OrderForm
from e_commerce.cart import Cart
from e_commerce.models import Product

@require_POST
@login_required(login_url='/login/')
def cart_add(request: HttpRequest, product_id: int):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product)
    messages.success(request, "Added to cart")
    return redirect(request.GET.get('next'))

def cart_remove(request: HttpRequest, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect(f'{TEMPLATE_FOLDER_NAME}:cart_detail')

@login_required(login_url='/login/')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def cart_detail(request: HttpRequest):
    cart = Cart(request)
    return render(request, f'{TEMPLATE_FOLDER_NAME}/cart.html', {'cart': cart, 'form': OrderForm()})

django-code/e_commerce_old/views/order.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.http import HttpRequest
from django.contrib import messages
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import login_required
from django.db import transaction
from urllib.parse import urlencode

from e_commerce.models import Order, OrderItem
from e_commerce.cart import Cart
from e_commerce.forms import OrderForm
from e_commerce.utils import generate_qr_code


TEMPLATE_FOLDER_NAME = 'e_commerce'

@require_POST
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def checkout(request: HttpRequest):
    cart = Cart(request)
    form = OrderForm(request.POST)

    if form.is_valid():
        try:
            with transaction.atomic():
                order: Order = form.save(commit=False)
                
                # Assign user if authenticated
                if request.user.is_authenticated:
                    order.user = request.user
                
                order.total_cost = cart.get_total_price()
                order.save()
                
                order_items_to_commit = []
                for item in cart:
                    product = item['product']
                    quantity = item['quantity']
                    
                    # Stock check
                    if product.stock < quantity:
                        raise ValueError(f"Not enough stock for {product.name}.")
                    

                    order_items_to_commit.append(
                        OrderItem(
                            order=order,
                            product=product,
                            quantity=quantity
                    ))
                    
                    # Deduct stock immediately
                    product.stock -= quantity
                    product.save()
                
                OrderItem.objects.bulk_create(order_items_to_commit) 
                
                # Clear cart and success message
                cart.clear()
                
                # make as success for demo purpose only
                order.payment_status = 'SUCCESS'
                order.save()

                return redirect(f'{TEMPLATE_FOLDER_NAME}:order_complete')

        except ValueError as e:
            # Handle out-of-stock
            print(e)
            messages.error(request, f"Order failed: {e}")
            return redirect(f'{TEMPLATE_FOLDER_NAME}:cart_detail')

        except Exception as e:
            print(e)
            # Handle general database/server errors
            messages.error(request, "An unexpected error occurred during checkout.")
            return redirect(f'{TEMPLATE_FOLDER_NAME}:cart_detail')
    
    # the form is NOT valid
    else:
        messages.error(request, "Please correct the errors in the form.")
        return render(request, f'{TEMPLATE_FOLDER_NAME}/cart.html', {'form': form, 'cart': cart})


@login_required(login_url='/login/')
def order_complete(request: HttpRequest, order_id: int):
    r"""GET request to view specific order"""

    try:
        order = Order.objects.get(id=order_id, user = request.user)

    except Order.DoesNotExist:
        messages.error(request, "Page not found.")
        return redirect('/')

    payment_info = {
        'acc': '000001111',
        'bank': 'myAppBank',
        'amount': order.total_cost,
        'orderId': order.id
    }
    payment_url = request.build_absolute_uri(f"/mobile/img?{urlencode(payment_info)}")
    qr_data_uri = generate_qr_code(payment_url)

    return render(
        request, 
        f'{TEMPLATE_FOLDER_NAME}/order_created.html', 
        {
            'order': order,
            'qr_data_uri': qr_data_uri
        }
    )

django-code/e_commerce_old/views/product.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_control
from django.http import HttpRequest
from django.core.paginator import Paginator
from django.db.models import Q, Prefetch
from django.contrib import messages

TEMPLATE_FOLDER_NAME = 'e_commerce'

from e_commerce.forms import ReviewForm
from e_commerce.models import Product, Order, Category

from django_ratelimit.decorators import ratelimit

@ratelimit(key='ip', rate='5/m', block=True)
def product_list(
        request: HttpRequest, 
        category_slug:str = None, 
        category_id: int = None
    ):
    
    parent_categories = Category.objects.filter(parent__isnull=True).order_by('name')
    categories_tree = parent_categories.prefetch_related(
        Prefetch('children', queryset=Category.objects.order_by('name'), to_attr='subcategories')
    )
    query = None

    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')

    if price_min is not None and price_max is not None:
        try:
            price_min = int(price_min)
            price_max = int(price_max)
            assert price_max > price_min
            print(price_min, price_max)
        except Exception as e:
            messages.error(request, "giá trị min max không hợp lệ")
            redirect(request.path)

    if category_slug is not None and category_id is not None:
        target_parent_cate = categories_tree.filter(id=category_id).first()

        if target_parent_cate:
            sub_categories = target_parent_cate.subcategories
            products = []
            if price_min is not None and price_max is not None:
                for sub_cate in sub_categories:
                    products_queryset = sub_cate.products.filter(price__gte=price_min).filter(price__lte=price_max)
                    products.extend(products_queryset.all())
            else:
                for sub_cate in sub_categories:
                    products.extend(sub_cate.products.all())
        else:
            taget_category = Category.objects.get(id = category_id, slug = category_slug)
            products = Product.objects.filter(category = taget_category)
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    else:
        query = request.GET.get('q')
        products = Product.objects.all().order_by('-created_at')
        if query:
            products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(
        request, 
        f'{TEMPLATE_FOLDER_NAME}/product/product_list.html', 
        {
            'page_obj': page_obj, 
            'query': query,
            'categories_tree': categories_tree
        }
    )

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def product_detail(request: HttpRequest, id:int):
    try:
        product = get_object_or_404(
            Product.objects.prefetch_related('reviews__user'),
            id=id
        )

        rounded_mean_rating = round(product.mean_rating*100,1) if product.mean_rating else None
        
        allow_to_review = None
        if request.user.is_authenticated:
            allow_to_review: bool = Order.objects.filter(
                user = request.user,
                items__product=product
            ).exists()
        else:
            allow_to_review = False

        return render(
            request, 
            f'{TEMPLATE_FOLDER_NAME}/product/product_detail.html', 
            {
                'product': product,
                'mean_rating': rounded_mean_rating,
                'allow_to_review': allow_to_review,
                'review_form': ReviewForm()
            }
        )
    except Exception as e:
        print(e)
        raise e

django-code/e_commerce_old/views/review.py
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.http import HttpRequest
from django.db import transaction
from django.contrib import messages

from e_commerce.forms import ReviewForm
from e_commerce.models import Review, Product

TEMPLATE_FOLDER_NAME = 'e_commerce'

@require_POST
def submit_review(request: HttpRequest, product_id: int):
    form = ReviewForm(request.POST)
    
    if form.is_valid():
        try:
            with transaction.atomic():
                
                review: Review = form.save(commit=False)

                product = Product.objects.get(id = product_id)
                review.product = product
                review.user = request.user

                review.save()
                return redirect(f'{TEMPLATE_FOLDER_NAME}:product_detail', id=product_id)

        except Product.DoesNotExist:
            messages.error(request, "Sản phẩm không tồn tại")
            return redirect(f'{TEMPLATE_FOLDER_NAME}:product_list')

        except Exception as e:
            messages.error(request, "Lỗi server")
            return redirect(f'{TEMPLATE_FOLDER_NAME}:product_detail', id=product_id)

    else:
        messages.error(request, "Lỗi form")
        return redirect(f'{TEMPLATE_FOLDER_NAME}:product_detail', id=product_id)

django-code/e_commerce_old/views/user.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpRequest
from django.contrib.auth.forms import PasswordChangeForm

from e_commerce.forms import AppUserCreationForm

TEMPLATE_FOLDER_NAME = 'e_commerce'

def register(request: HttpRequest):
    if request.method == 'POST':
        form = AppUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user) 
            return redirect(f'/')
    else:
        form = AppUserCreationForm()
    
    return render(request, f'{TEMPLATE_FOLDER_NAME}/register.html', {'form': form})

class CustomLoginView(UserPassesTestMixin, LoginView):
    template_name = f'{TEMPLATE_FOLDER_NAME}/login.html'

    def test_func(self)->bool:
        r"""return True if the user is NOT authenticated"""
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        next_url = self.request.GET.get('next')

        if next_url:
            return redirect(next_url)
        
        return redirect(f'/')

class CustomPwdChangeView(PasswordChangeView):
    template_name = f'{TEMPLATE_FOLDER_NAME}/pwd_change.html'
    success_url= '/'
    form_class=PasswordChangeForm
    

django-code/e_commerce_old/templates/e_commerce/product/category_nav.component.html
{% load static %}
<nav class="category-menu">
    <p class="category-menu-header"><strong>Khám phá theo danh mục</strong></p>
    <div class="parent-list">
        
        {% for parent_cat in categories_tree %}
            <div class="parent-item">

                {% comment %} image as button and a tag must be inline {% endcomment %}
                <div class="parent-item-head">
                    <a 
                        href="{% url 'e_commerce:category_product_list' parent_cat.slug parent_cat.id %}" 
                        class="parent-link"
                        >
                        <strong>{{ parent_cat.name }}</strong>
                    </a>
                    
                    <div
                        class="flip-container"
                        id="flip-button"
                        type="button"
                        aria-expanded="false"
                        aria-controls="collapse-{{ parent_cat.id }}"
                        data-bs-toggle="collapse" 
                        data-bs-target="#collapse-{{ parent_cat.id }}"
                        >
                        <div class="flipper">
                            <img 
                                src="{% static 'e_commerce/image/nav_arrow.png' %}" 
                                alt="category-nav-icon" 
                                class="category-nav-icon"
                            >
                        </div>
                    </div>
                </div>
                
                <div class="collapse" id="collapse-{{ parent_cat.id }}">
                    {% if parent_cat.subcategories %}
                        <div class="child-panel">
                            <ul class="child-list">
                                {% for child_cat in parent_cat.subcategories %}
                                    <li class="child-item">
                                        <a 
                                            href="{% url 'e_commerce:category_product_list' child_cat.slug child_cat.id %}" 
                                            class="child-link"
                                            >
                                            {{ child_cat.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                                
                            </ul>
                        </div>
                    {% endif %}
                </div>
            
            </div>

        {% endfor %}

    </div>
</nav>

django-code/e_commerce_old/templates/e_commerce/product/listing.component.html
{% load l10n %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in page_obj %}
        <div class="col">
            <div class="card h-100">
                {% if product.thumbnail_url %}
                    <img 
                        src="{{ product.thumbnail_url }}"
                        class="card-img-top listing-img-thumbnail" 
                        alt="{{ product.name }}"
                        >
                {% else %}
                    <div class="bg-light d-flex align-items-center justify-content-center" style="height: 200px;">
                        <span class="text-muted">No Image</span>
                    </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    
                    <p class="card-text text-danger">
                        {% localize on %}
                            {{ product.price }}
                        {% endlocalize %} đ
                    </p>
                    <a href="{% url 'e_commerce:product_detail' product.id %}" class="btn btn-primary w-100">Xem chi tiết</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <p class="text-center text-muted">Không tìm thấy sản phẩm nào</p>
        </div>
    {% endfor %}
</div>

django-code/e_commerce_old/templates/e_commerce/product/product_detail.html
{% extends '../base.html' %}

{% block title %}{{ product.name }} - E-commerce Store{% endblock %}

{% block content %}
{% load l10n %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <div class="product-image-gallery">
                <div class="main-image-display mb-3 text-center">
                    {% if product.images.all %}
                        <img 
                            src="{{ product.images.first.image_url }}" 
                            alt="{{ product.name }} main image" 
                            class="img-fluid rounded shadow-sm max-width: 40%" 
                            id="mainProductImage"
                        >
                    {% else %}
                        <img 
                            src="https://via.placeholder.com/600x600?text=No+Image" 
                            alt="No Image Available" 
                            class="img-fluid rounded shadow-sm"
                        >
                    {% endif %}
                </div>
            
                <div class="thumbnail-strip d-flex flex-wrap justify-content-center gap-2">
                    {% for img in product.images.all %}
                        <img 
                            src="{{ img.image_url }}" 
                            alt="{{ product.name }} thumbnail {{ forloop.counter }}" 
                            class="img-thumbnail rounded-3 thumbnail-item {% if forloop.first %}active{% endif %}" 
                            data-large-image="{{ img.image_url }}"
                        >
                    {% empty %}
                    {% endfor %}
                </div>
            </div>

        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title fw-bold">{{ product.name }}</h2>

                {% if mean_rating %}
                    <div style="display: flex;align-items: center;width: 30vw;">
                        <h5 class="card-text text-black m-3">
                            {% localize off %}
                                {{ mean_rating }}
                            {% endlocalize %} %
                        </h5>
                        <i 
                            class="bi bi-emoji-smile" 
                            style="color: greenyellow;font-size: 2rem;display: block;margin-right: 1rem;"
                            >
                        </i>
                        <i 
                            class="bi bi-info-circle"
                            data-bs-placement="right" 
                            data-bs-toggle="tooltip"
                            data-bs-title="Tỷ lệ người dùng cảm thấy hài lòng"
                            >
                        </i>
                    </div>
                {% endif %}
                
                <h3 class="card-text text-danger mb-3">
                    {% localize on %}
                        {{ product.price }}
                    {% endlocalize %} đ
                </h3>
                <p class="card-text">{{ product.description | safe }}</p>

                <form method="post" action="{% url 'e_commerce:cart_add' product.id %}?next={{ request.path }}" class="logout-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-primary mt-3">Thêm vào giỏ hàng</button>
                </form>
            </div>

            <div class="card-body">
                <h4 class="card-title mb-4 border-bottom pb-2">
                    Nhận xét khách hàng (<span class="text-primary">{{ product.reviews.count }}</span>)
                </h4>

                {% if user.is_authenticated %}
                    {% comment %} for registered user {% endcomment %}

                    {% comment %} loading reviews {% endcomment %}
                    {% if product.reviews.all %}
                        <div class="review-list">
                            
                            {% for review in product.reviews.all %}
                                <div class="card shadow-sm mb-4 review-card">
                                    <div class="card-body">
                                        
                                        <div class="d-flex justify-content-between align-items-center mb-2 border-bottom pb-2">
                                            <div class="fw-bold text-dark">
                                                <i class="bi bi-person-circle me-1"></i> User: {{ review.user.username }}
                                            </div>
                                        </div>

                                        <p class="card-text text-muted mb-0">
                                            {{ review.content }}
                                        </p>

                                    </div>
                                </div>
                            {% endfor %}
                
                        </div>
                    {% else %}
                        <p class="text-center text-muted py-3">Chưa có review nào cho sản phẩm này!</p>
                    {% endif %}

                    {% comment %} load review form with condition {% endcomment %}
                    {% if allow_to_review %}
                        {% include "./review_form.html" %}
                    {% endif %}

                {% else %}
                {% comment %} for anonymous user {% endcomment %}
                    <div style="display: flex;justify-content: center;">
                        <a class="nav-link"
                            href="{% url 'e_commerce:login' %}?next={{ request.path }}">
                            <u>Đăng nhập</u>
                        </a>
                        <p class="card-text ms-1">để xem tất cả review</p>
                    </div>
                {% endif %}

            </div>


        </div>
    </div>
</div>
{% endblock %}

django-code/e_commerce_old/templates/e_commerce/product/product_list.html
{% extends '../base.html' %}

{% block title %}Products - E-commerce Store{% endblock %}

{% block content %}

{% load static %}
{% load l10n %}

<div class="row mb-4">
    <div class="col-md-3">
        <h1>Products</h1>
    </div>
    <div class="col-md-9">
        <div class="row">
            <form class="d-flex" action="{% url 'e_commerce:product_list' %}" method="get">
                <div class="input-group mb-3">
                    <input class="form-control me-2" type="search" name="q" placeholder="từ khóa tìm kiếm ..."
                        value="{{ query|default:'' }}">

                    <button class="btn btn-outline-primary" type="submit">Tìm kiếm</button>
                </div>
            </form>
        </div>        
    </div>
</div>

<div class="row mb-4">
    <div class="col-md-3">
    {% comment %} left panel for category navigation {% endcomment %}
            {% include "./filter.component.html" %}
            {% include "./category_nav.component.html" %}
    </div>

    <div class="col-md-9">
    {% comment %} right panel for show product list {% endcomment %}
        {% include "./listing.component.html" %}
    </div>
</div>


<div class="mt-4">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1{% if query %}&q={{ query }}{% endif %}">&laquo;
                            First</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                        href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">Next</a></li>
                <li class="page-item"><a class="page-link"
                        href="?page={{ page_obj.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Last
                        &raquo;</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}