django-code/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import CustomLoginView, CustomPwdChangeView, register

app_name = 'accounts'

urlpatterns = [
    path('login', CustomLoginView.as_view(),name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('register', register, name='register'),
    path('pwd_change', CustomPwdChangeView.as_view(),name='pwd_change'),
]

django-code/carts/urls.py
from django.urls import path

from carts.views import cart_detail, cart_add, cart_remove

app_name = 'carts'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove')
]

django-code/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('products.urls')),
    path('health', include('health_check.urls')),
]

django-code/products/urls.py
from django.urls import path

from products.views import product_list, product_detail

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('category/<slug:category_slug>/<int:category_id>', product_list, name='category_product_list'),
    path('detail/<int:id>', product_detail, name='product_detail'),
]

django-code/products/models.py
from django.db import models
import uuid

################## Category and Product ##################
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, unique=False)
    created_at = models.DateTimeField(auto_now_add=True)

    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,               
        blank=True,              
        related_name='children',
    )

    class Meta:
        ordering = ['name']
        unique_together = ('slug', 'parent',) 
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    r"""
    Schema for product table
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, related_name="products")
    description = models.TextField(blank=True)
    brand_name = models.CharField(max_length=100)
    price = models.IntegerField()
    stock = models.IntegerField()
    is_active = models.BooleanField()
    thumbnail_url = models.URLField(null= False)
    mean_rating = models.FloatField(null= True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ProductImg(models.Model):
    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4,
        editable=False
    )
    product = models.ForeignKey(Product, on_delete= models.CASCADE, related_name = "images")
    image_url = models.URLField(null= False)
    created_at = models.DateTimeField(auto_now_add=True)

django-code/e_commerce_old/views/product.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_control
from django.http import HttpRequest
from django.core.paginator import Paginator
from django.db.models import Q, Prefetch
from django.contrib import messages

TEMPLATE_FOLDER_NAME = 'e_commerce'

from e_commerce.forms import ReviewForm
from e_commerce.models import Product, Order, Category

from django_ratelimit.decorators import ratelimit

@ratelimit(key='ip', rate='5/m', block=True)
def product_list(
        request: HttpRequest, 
        category_slug:str = None, 
        category_id: int = None
    ):
    
    parent_categories = Category.objects.filter(parent__isnull=True).order_by('name')
    categories_tree = parent_categories.prefetch_related(
        Prefetch('children', queryset=Category.objects.order_by('name'), to_attr='subcategories')
    )
    query = None

    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')

    if price_min is not None and price_max is not None:
        try:
            price_min = int(price_min)
            price_max = int(price_max)
            assert price_max > price_min
            print(price_min, price_max)
        except Exception as e:
            messages.error(request, "giá trị min max không hợp lệ")
            redirect(request.path)

    if category_slug is not None and category_id is not None:
        target_parent_cate = categories_tree.filter(id=category_id).first()

        if target_parent_cate:
            sub_categories = target_parent_cate.subcategories
            products = []
            if price_min is not None and price_max is not None:
                for sub_cate in sub_categories:
                    products_queryset = sub_cate.products.filter(price__gte=price_min).filter(price__lte=price_max)
                    products.extend(products_queryset.all())
            else:
                for sub_cate in sub_categories:
                    products.extend(sub_cate.products.all())
        else:
            taget_category = Category.objects.get(id = category_id, slug = category_slug)
            products = Product.objects.filter(category = taget_category)
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    else:
        query = request.GET.get('q')
        products = Product.objects.all().order_by('-created_at')
        if query:
            products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(
        request, 
        f'{TEMPLATE_FOLDER_NAME}/product/product_list.html', 
        {
            'page_obj': page_obj, 
            'query': query,
            'categories_tree': categories_tree
        }
    )

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def product_detail(request: HttpRequest, id:int):
    try:
        product = get_object_or_404(
            Product.objects.prefetch_related('reviews__user'),
            id=id
        )

        rounded_mean_rating = round(product.mean_rating*100,1) if product.mean_rating else None
        
        allow_to_review = None
        if request.user.is_authenticated:
            allow_to_review: bool = Order.objects.filter(
                user = request.user,
                items__product=product
            ).exists()
        else:
            allow_to_review = False

        return render(
            request, 
            f'{TEMPLATE_FOLDER_NAME}/product/product_detail.html', 
            {
                'product': product,
                'mean_rating': rounded_mean_rating,
                'allow_to_review': allow_to_review,
                'review_form': ReviewForm()
            }
        )
    except Exception as e:
        print(e)
        raise e

django-code/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_control
from django.http import HttpRequest
from django.core.paginator import Paginator
from django.db.models import Q, Prefetch
from django.contrib import messages
from django_ratelimit.decorators import ratelimit

TEMPLATE_FOLDER_NAME = 'products'

from reviews.forms import ReviewForm
from products.models import Product, Category
from orders.models import Order

@ratelimit(key='ip', rate='5/m', block=True)
def product_list(
        request: HttpRequest, 
        category_slug:str = None, 
        category_id: int = None
    ):
    
    parent_categories = Category.objects.filter(parent__isnull=True).order_by('name')
    categories_tree = parent_categories.prefetch_related(
        Prefetch('children', queryset=Category.objects.order_by('name'), to_attr='subcategories')
    )
    query = None

    price_min = request.GET.get('price_min')
    price_max = request.GET.get('price_max')

    if price_min is not None and price_max is not None:
        try:
            price_min = int(price_min)
            price_max = int(price_max)
            assert price_max > price_min
            print(price_min, price_max)
        except Exception as e:
            messages.error(request, "giá trị min max không hợp lệ")
            redirect(request.path)

    if category_slug is not None and category_id is not None:
        target_parent_cate = categories_tree.filter(id=category_id).first()

        if target_parent_cate:
            sub_categories = target_parent_cate.subcategories
            products = []
            if price_min is not None and price_max is not None:
                for sub_cate in sub_categories:
                    products_queryset = sub_cate.products.filter(price__gte=price_min).filter(price__lte=price_max)
                    products.extend(products_queryset.all())
            else:
                for sub_cate in sub_categories:
                    products.extend(sub_cate.products.all())
        else:
            taget_category = Category.objects.get(id = category_id, slug = category_slug)
            products = Product.objects.filter(category = taget_category)
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    else:
        query = request.GET.get('q')
        products = Product.objects.all().order_by('-created_at')
        if query:
            products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
            if price_min is not None and price_max is not None:
                products = products.filter(price__gte=price_min).filter(price__lte=price_max)

    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(
        request, 
        f'{TEMPLATE_FOLDER_NAME}/product_list.html', 
        {
            'page_obj': page_obj, 
            'query': query,
            'categories_tree': categories_tree
        }
    )

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def product_detail(request: HttpRequest, id:int):
    try:
        product = get_object_or_404(
            Product.objects.prefetch_related('reviews__user'),
            id=id
        )

        rounded_mean_rating = round(product.mean_rating*100,1) if product.mean_rating is not None else None
        
        allow_to_review = None
        if request.user.is_authenticated:
            allow_to_review: bool = Order.objects.filter(
                user = request.user,
                items__product=product
            ).exists()
        else:
            allow_to_review = False

        return render(
            request, 
            f'{TEMPLATE_FOLDER_NAME}/product_detail.html', 
            {
                'product': product,
                'mean_rating': rounded_mean_rating,
                'allow_to_review': allow_to_review,
                'review_form': ReviewForm()
            }
        )
    except Exception as e:
        print(e)
        raise e

django-code/products/templates/products/category_nav.component.html
{% load static %}
<nav class="category-menu">
    <p class="category-menu-header"><strong>Khám phá theo danh mục</strong></p>
    <div class="parent-list">
        
        {% for parent_cat in categories_tree %}
            <div class="parent-item">

                {% comment %} image as button and a tag must be inline {% endcomment %}
                <div class="parent-item-head">
                    <a 
                        href="{% url 'products:category_product_list' parent_cat.slug parent_cat.id %}" 
                        class="parent-link"
                        >
                        <strong>{{ parent_cat.name }}</strong>
                    </a>
                    
                    <div
                        class="flip-container"
                        id="flip-button"
                        type="button"
                        aria-expanded="false"
                        aria-controls="collapse-{{ parent_cat.id }}"
                        data-bs-toggle="collapse" 
                        data-bs-target="#collapse-{{ parent_cat.id }}"
                        >
                        <div class="flipper">
                            <img 
                                src="{% static 'products/image/nav_arrow.png' %}" 
                                alt="category-nav-icon" 
                                class="category-nav-icon"
                            >
                        </div>
                    </div>
                </div>
                
                <div class="collapse" id="collapse-{{ parent_cat.id }}">
                    {% if parent_cat.subcategories %}
                        <div class="child-panel">
                            <ul class="child-list">
                                {% for child_cat in parent_cat.subcategories %}
                                    <li class="child-item">
                                        <a 
                                            href="{% url 'products:category_product_list' child_cat.slug child_cat.id %}" 
                                            class="child-link"
                                            >
                                            {{ child_cat.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                                
                            </ul>
                        </div>
                    {% endif %}
                </div>
            
            </div>

        {% endfor %}

    </div>
</nav>

django-code/products/templates/products/filter.component.html
{% load static %}
<button 
    type="button" 
    class="btn btn-outline-primary" 
    data-bs-toggle="modal" 
    data-bs-target="#priceFilterModal"
    id="price-filter-button"
    >
    <img 
        src="{% static 'products/image/filter.png' %}" 
        alt="price-filter-icon" 
        class="price-filter-icon"
    >
    <p id="price-filter-button-label">Lọc theo khoảng giá</p>
</button>

<!-- Modal for price filter-->
<div 
    class="modal fade" 
    id="priceFilterModal" 
    tabindex="-1" 
    aria-labelledby="priceFilterModalLabel"
    aria-hidden="true"
    >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="priceFilterModalLabel">Khoảng giá</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form 
                    method="get" 
                    action="{{ request.path }}"
                    >
                    
                    <div class="input-group">
                        <span class="input-group-text">Từ</span>
                        <input 
                            type="text" 
                            class="form-control js-localize-input"
                            placeholder="nhỏ nhất"
                            name="price_min" 
                            id="price_min" 
                            value="{{ query.price_min|default:'' }}"
                            >
                    
                        <span class="input-group-text">đến</span>
                        <input 
                            type="text" 
                            class="form-control js-localize-input"
                            placeholder="lớn nhất" 
                            name="price_max" 
                            id="price_max" 
                            value="{{ query.price_max|default:'' }}"
                            >
                        <span class="input-group-text">đ</span>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary mt-3" data-bs-dismiss="modal">Áp dụng</button>
                </form>
                
                
            </div>
        </div>
    </div>
</div>

django-code/products/templates/products/listing.component.html
{% load l10n %}
<div class="row row-cols-1 row-cols-md-3 g-4 listing-section">
    {% for product in page_obj %}
        <div class="col">
            <div class="card h-100">
                {% if product.thumbnail_url %}
                    <img 
                        src="{{ product.thumbnail_url }}"
                        class="card-img-top listing-img-thumbnail" 
                        alt="{{ product.name }}"
                        >
                {% else %}
                    <div class="bg-light d-flex listing-img-thumbnail-failed">
                        <span class="text-muted">No Image</span>
                    </div>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    
                    <p class="card-text text-danger">
                        {% localize on %}
                            {{ product.price }}
                        {% endlocalize %} đ
                    </p>
                    <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary w-100">Xem chi tiết</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <p class="text-center text-muted">Không tìm thấy sản phẩm nào</p>
        </div>
    {% endfor %}
</div>

django-code/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }} - E-commerce Store{% endblock %}

{% block content %}
{% load l10n %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <div class="product-image-gallery">
                <div class="main-image-display mb-3 text-center">
                    {% if product.images.all %}
                        <img 
                            src="{{ product.images.first.image_url }}" 
                            alt="{{ product.name }} main image" 
                            class="img-fluid rounded shadow-sm max-width: 40%" 
                            id="mainProductImage"
                        >
                    {% else %}
                        <img 
                            src="https://via.placeholder.com/600x600?text=No+Image" 
                            alt="No Image Available" 
                            class="img-fluid rounded shadow-sm"
                        >
                    {% endif %}
                </div>
            
                <div class="thumbnail-strip d-flex flex-wrap justify-content-center gap-2">
                    {% for img in product.images.all %}
                        <img 
                            src="{{ img.image_url }}" 
                            alt="{{ product.name }} thumbnail {{ forloop.counter }}" 
                            class="img-thumbnail rounded-3 thumbnail-item {% if forloop.first %}active{% endif %}" 
                            data-large-image="{{ img.image_url }}"
                        >
                    {% empty %}
                    {% endfor %}
                </div>
            </div>

        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title fw-bold">{{ product.name }}</h2>

                {% if mean_rating is not None %}
                    <div class="mean-rating-container">
                        <h5 class="card-text text-black m-3">
                            {% localize off %}
                                {{ mean_rating }}
                            {% endlocalize %} %
                        </h5>
                        <i 
                            id="emoji-smile-icon"
                            class="bi bi-emoji-smile" 
                            >
                        </i>
                        <i 
                            class="bi bi-info-circle"
                            data-bs-placement="right" 
                            data-bs-toggle="tooltip"
                            data-bs-title="Tỷ lệ người dùng cảm thấy hài lòng"
                            >
                        </i>
                    </div>
                {% endif %}
                
                <h3 class="card-text text-danger mb-3">
                    {% localize on %}
                        {{ product.price }}
                    {% endlocalize %} đ
                </h3>
                <div class="card-text detail-description">{{ product.description | safe }}</div>

                <form method="post" action="{% url 'carts:cart_add' product.id %}?next={{ request.path }}" class="logout-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-primary mt-3">Thêm vào giỏ hàng</button>
                </form>
            </div>

            <div class="card-body">
                {% if not allow_to_review %}
                    <p class="text-center">mua sản phẩm để được viết review</p>
                {% endif %}

                <h4 class="card-title mb-4 border-bottom pb-2">
                    Nhận xét khách hàng (<span class="text-primary">{{ product.reviews.count }}</span>)
                </h4>

                {% if user.is_authenticated %}
                    {% comment %} for registered user {% endcomment %}

                    {% comment %} loading reviews {% endcomment %}
                    {% if product.reviews.all %}
                        <div class="review-list">
                            
                            {% for review in product.reviews.all %}
                                <div class="card shadow-sm mb-4 review-card">
                                    <div class="card-body">
                                        
                                        <div class="d-flex justify-content-between align-items-center mb-2 border-bottom pb-2">
                                            <div class="fw-bold text-dark">
                                                <i class="bi bi-person-circle me-1"></i> User: {{ review.user.username }}
                                            </div>
                                        </div>

                                        <p class="card-text text-muted mb-0">
                                            {{ review.content }}
                                        </p>

                                    </div>
                                </div>
                            {% endfor %}
                
                        </div>
                    {% else %}
                        <p class="text-center text-muted py-3">Chưa có review nào cho sản phẩm này!</p>
                    {% endif %}

                    {% comment %} load review form with condition {% endcomment %}
                    {% if allow_to_review %}
                        {% include "views/review_form.html" %}
                    {% endif %}

                {% else %}
                {% comment %} for anonymous user {% endcomment %}
                    <div class="signin-alert">
                        <a class="nav-link"
                            href="{% url 'accounts:login' %}?next={{ request.path }}">
                            <u>Đăng nhập</u>
                        </a>
                        <p class="card-text ms-1">để xem tất cả review</p>
                    </div>
                {% endif %}

            </div>


        </div>
    </div>
</div>
{% endblock %}

django-code/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %}Products - E-commerce Store{% endblock %}

{% block content %}

{% load static %}
{% load l10n %}

<div class="row mb-4">
    <div class="col-md-3">
        <h1>Products</h1>
    </div>
    <div class="col-md-9">
        <div class="row">
            <form class="d-flex" action="{% url 'products:product_list' %}" method="get">
                <div class="input-group mb-3">
                    <input class="form-control me-2" type="search" name="q" placeholder="từ khóa tìm kiếm ..."
                        value="{{ query|default:'' }}">

                    <button class="btn btn-outline-primary" type="submit">Tìm kiếm</button>
                </div>
            </form>
        </div>        
    </div>
</div>

<div class="row mb-4">
    <div class="col-md-3">
    {% comment %} left panel for category navigation {% endcomment %}
            {% include "./filter.component.html" %}
            {% include "./category_nav.component.html" %}
    </div>

    <div class="col-md-9">
    {% comment %} right panel for show product list {% endcomment %}
        {% include "./listing.component.html" %}
    </div>
</div>


<div class="mt-4">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1{% if query %}&q={{ query }}{% endif %}">&laquo;
                            First</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <span class="page-link">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                        href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">Next</a></li>
                <li class="page-item"><a class="page-link"
                        href="?page={{ page_obj.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Last
                        &raquo;</a></li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}